### ISSUE TITLE
Update/publish version >=3.25.1?

### ISSUE THREAD

**Issue by sosimon** [travelaudience/docker-nexus#49]
Currently using latest which is 3.23 and encountering the following:

```
This version of Nexus Repository Manager is vulnerable to a critical remote code execution security vulnerability.

We recommend immediate upgrade to 3.25.1 or later, especially if this is a public instance.
```

I'm happy to do a PR and update the Dockerfile if that helps.

P.S. thanks for publishing this image - great help! :)

**Comment by TAvardit** [comment]
Hi, I just merged a PR for `3.25.1` and will tag it so it will be built. 
I merged it without testing for compatibility with our other Nexus docker images ( backup and proxy) because it is a security fix.
I will test it later and maybe upgrade to `3.26.1` as well. 

Happy to give back to the community. :D
